pcd2pgm:
  ros__parameters:
    pcd_file: /home/sb/origin_nav2025_test/src/localization/Point-LIO-grid_map_ros2/PCD/scans.pcd
    odom_to_lidar_odom: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    # odom_to_lidar_odom: [-0.16, 0.0, -0.18, -0.523599, 0.0, -1.5707963]
    flag_pass_through: false
    map_resolution: 0.05
    map_topic_name: map
    thre_radius: 0.1
    thre_z_max: 10.0
    thre_z_min: -0.6
    thres_point_count: 10
