/**:
  ros__parameters:
    common:
      con_frame: false
      con_frame_num: 1
      cut_frame: false
      cut_frame_time_interval: 0.1
      imu_topic: /livox/imu
      lid_topic: /livox/lidar
      time_diff_lidar_to_imu: 0.001792
    filter_size_map: 0.3
    filter_size_surf: 0.3
    mapping:
      acc_cov_input: 0.001
      acc_cov_output: 500.0
      acc_norm: 1.0
      b_acc_cov: 0.01
      b_gyr_cov: 0.01
      det_range: 100.0
      extrinsic_R:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      extrinsic_T:
      - 0.011
      - 0.02329
      - -0.04412
      extrinsic_est_en: false
      fov_degree: 360.0
      gravity:
      - 0.0
      - 0.0
      - -9.800291
      gravity_align: true
      gravity_init:
      - 0.0
      - 0.0
      - -9.81
      gyr_cov_input: 0.001
      gyr_cov_output: 1000.0
      imu_en: true
      imu_meas_acc_cov: 0.01
      imu_meas_omg_cov: 0.01
      imu_time_inte: 0.005
      ivox_grid_resolution: 2.0
      lidar_meas_cov: 0.001
      match_s: 81.0
      plane_thr: 0.05
      satu_acc: 4.0
      satu_gyro: 35.0
      start_in_aggressive_motion: false
    odometry:
      publish_odometry_without_downsample: false
    pcd_save:
      interval: -1
      pcd_save_en: false
    point_filter_num: 1
    preprocess:
      blind: 0.1
      lidar_type: 1
      scan_line: 6
      timestamp_unit: 1
    publish:
      path_en: true
      scan_bodyframe_pub_en: false
      scan_publish_en: true
